#:schema node_modules/wrangler/config-schema.json
name = "guardian-demo-2"
main = ".open-next/worker.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Uncomment and update for custom domain
# routes = [
#   { pattern = "guardian-demo-2.com", custom_domain = true }
# ]
