#:schema node_modules/wrangler/config-schema.json
name = "guardian-demo-2"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

# Required for Cloudflare Pages
pages_build_output_dir = ".open-next"

# Uncomment and update for custom domain
# routes = [
#   { pattern = "guardian-demo-2.com", custom_domain = true }
# ]
